#!/bin/bash

# The data remain available even if the container is stopped with "docker stop"
# or deleted with "docker rm"

# To remove the container shared directory use "docker rm -v <container-name>" 

if [ "$#" -ne 1 ] ; then
   echo "Usage: Need the container name as argument"
else
   echo $(sudo docker inspect -f '{{index .Volumes "/etc/quagga"}}' $1)
fi
